---
title: "RUE Fodder Beet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)

```

Read

```{r Read, include=FALSE, echo=FALSE}

fileFolder <- "C:\\GitHubRepos\\FodderBeetNNI\\"

info <- read.table(paste0(fileFolder, "NNI_foddetB.txt"), header = TRUE)
#C:\GitHubRepos\NNI_fodderB\NNI_foddetB.txt
str(info)

info$N_Treatments <- as.factor(info$N_Treatments)
info$Rep <- as.factor(info$Rep)
info$Date <- dmy(info$Date)
#info$Total_DM <- info$Total_DM*100 # kg/ha to g/m2
info <- info %>%
  rowwise() %>% 
  mutate(Total_DM = sum(Lamina_DM, Petiole_DM, Bulb_DM, Dead_DM, na.rm=TRUE)) %>% 
  mutate(
    Lamina_N_tot = Lamina_N_con/100 * Lamina_DM, # in t/ha
    Petiole_N_tot = Petiole_N_con/100 * Petiole_DM,
    Dead_leaf_N_tot = Dead_leaf_N_con/100  * Dead_DM,
    Bulb_N_tot = Bulb_N_con/100 * Bulb_DM
  ) %>% 
  mutate(Total_N_conc =
         sum(Lamina_N_tot , 
              Petiole_N_tot , 
              Dead_leaf_N_tot , 
              Bulb_N_tot,na.rm=TRUE)/Total_DM*100
)
  


summary(info)
head(info)
str(info)
```


```{r SetUpDfGraph, echo=FALSE, warning=FALSE}

info_graph <- info %>%
  tidyr::gather("Variable", "Value",7:20) %>%
  mutate(Variable = as.factor(Variable))

summary(info_graph)
  
```


```{r}

# mf_labeller <- function(var, value){ # lifted bodily from the R Cookbook
#     value <- as.character(value)
#     if (var=="Variable") {
#         value[value=="Bulb_DM"]   <- "Storage root"
#         value[value=="Dead_DM"]   <- "Senesced"
#         value[value=="Lamina_DM"]   <- "Leaves"
#         value[value=="Petiole_DM"]   <- "Petioles"
#         value[value=="Total_DM"]   <- "Total biomass"
#     }
#     return(value)
# }



```



## Time series

```{r TimeSeries, echo=FALSE,fig.height=10, fig.width=8}

# add totals
# biomass
info_graph %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Date, Variable) %>%
#  filter(Variable != "Bulb_DM", Variable != "Shoot_DM") %>%
  filter(grepl("_DM", Variable)) %>%
  filter(Variable == "Total_DM") %>%
  dplyr::select(-DAS,-Rep) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Date,y=mean, 
             shape=factor(Water_Treatments),
             colour=factor(N_Treatments))) +
  geom_point() +
  geom_line(aes(linetype = factor(Water_Treatments))) +
  facet_grid(Variable~Experiment, scales= "free") +
  ylab("Total biomass (t/ha)") +
  xlab("Date") +
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2), 
                width=0.5)  +
#  theme(legend.title=element_blank()) +
  labs(linetype="Water regime", colour="N fertiliser (kg/ha)", shape="Water regime") +
  theme(strip.text.y = element_blank())

# y(0,25)


# percentage of biomass FIXME
info_graph %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Date, Variable) %>%
#  filter(Variable != "Bulb_DM", Variable != "Shoot_DM") %>%
  filter(grepl("_DM", Variable)) %>%
  tidyr::spread(Variable, Value) %>%
  tidyr::gather("Variable", "Value",7:10) %>%
  mutate(Variable =  factor(Variable, levels = c("Bulb_DM", "Lamina_DM", "Petiole_DM", "Dead_DM"), 
                                                labels = c("Storage root", "Leaves", "Petioles", "Senesced"))) %>%
  mutate(Bio_perc = Value/Total_DM*100) %>%
  dplyr::select(Experiment, N_Treatments, Water_Treatments, Date, Variable, Bio_perc) %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Date, Variable) %>%
  summarise(perc_mean = mean(Bio_perc), perc_sd = sd(Bio_perc)) %>%
  ggplot(aes(x=Date,y=perc_mean, 
             shape=factor(Water_Treatments),
             colour=factor(N_Treatments))) +
  geom_point() +
  geom_line(aes(linetype = factor(Water_Treatments))) +
  facet_grid(Variable~Experiment+Water_Treatments, scales= "free") +
  ylab("Percentage of total dry matter (%)") +
  xlab("Date") +
#  theme(legend.title=element_blank()) +
  labs(linetype="Water regime", colour="N fertiliser (kg/ha)", shape="Water regime") +
 # theme(strip.text.y = element_blank()) +
  geom_errorbar(aes(ymin=perc_mean-perc_sd/2,
                    ymax=perc_mean+perc_sd/2), 
                width=0.5)


# concentrations
info_graph %>%
  filter(grepl("_con", Variable)) %>%
#  summary()
  mutate(Variable =  factor(Variable, levels = c("Total_N_conc","Bulb_N_con", "Lamina_N_con", "Petiole_N_con", "Dead_leaf_N_con"), 
                                                labels = c("Total biomass","Storage root", "Leaves", "Petioles", "Senesced"))) %>%
  dplyr::select(-DAS,-Rep) %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Date, Variable) %>%
#  filter(Variable != "Bulb_DM", Variable != "Shoot_DM") %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Date,y=mean, 
             shape=factor(Water_Treatments),
             colour=factor(N_Treatments))) +
  geom_point() +
  geom_line(aes(linetype = factor(Water_Treatments))) +
  facet_grid(Variable~Experiment+Water_Treatments, scales= "free") +
  labs(linetype="Water regime", colour="N fertiliser (kg/ha)", shape="Water regime") +
  ylab("Nitrogen concentration (%)") +
  xlab("Date") +
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2), 
                width=0.5) # +
 # ylim(0,5)


# N amounts
info_graph %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Date, Variable) %>%
#  filter(Variable != "Bulb_DM", Variable != "Shoot_DM") %>%
  filter(grepl("_tot", Variable)) %>%
  dplyr::select(-DAS,-Rep) %>%
  summarise_each(funs(mean,sd)) %>%
  mutate(mean = mean*1000, sd = sd*1000)  %>% # t/ha to kg/ha
  ggplot(aes(x=Date,y=mean, 
             shape=factor(Water_Treatments),
             colour=factor(N_Treatments))) +
  geom_point() +
  geom_line(aes(linetype = factor(Water_Treatments))) +
  facet_grid(Variable~Experiment+Water_Treatments, scales= "free") +
  ylab("Nitrogen amount per plant organ (kg/ha)") +
  xlab("Date") +
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2), 
                width=0.25) # +
  

```

## N% decay


```{r GraphNDecay, echo=FALSE,fig.height=10, fig.width=8}

info_graph %>%
  filter(grepl("_con", Variable) | Variable == "Total_DM") %>%
    tidyr::spread(Variable, Value) %>%
  mutate(TotalBio = Total_DM) %>% # FIXME: quick fix for easy picking of column 
  tidyr::gather("Variable", "Value",7:(ncol(.)-1)) %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Date, Variable) %>%
  dplyr::select(-DAS,-Rep) %>%
  summarise_each(funs(mean,sd)) %>%
  filter(Variable != "Total_DM") %>%
  ggplot(aes(x=TotalBio_mean,y=Value_mean, 
             shape=factor(Water_Treatments),
             colour=factor(N_Treatments))) +
  geom_point() +
  geom_line(aes(linetype = factor(Water_Treatments))) +
  facet_grid(Variable~Experiment+Water_Treatments, scales= "free") +
  ylab("Nitrogen concentration in tissue (%)") +
  xlab("Total crop biomass (t/ha)") +
  geom_errorbar(aes(ymin=Value_mean-Value_sd/2,
                    ymax=Value_mean+Value_sd/2), 
                width=0.25)  +
   ylim(0,5)


```
